name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-24.04
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download build for x86_64-windows
        uses: actions/download-artifact@v4
        with:
          name: build-x86_64-windows

      - name: Download build for x86_64-linux
        uses: actions/download-artifact@v4
        with:
          name: build-x86_64-linux

      - name: Download build for aarch64-linux
        uses: actions/download-artifact@v4
        with:
          name: build-aarch64-linux

      - name: Download build for aarch64-macos
        uses: actions/download-artifact@v4
        with:
          name: build-aarch64-macos

      - name: Release
        run: |
          gh release create \
            -t "Banjo $(date -Idate)" \
            -n "Banjo Release $(date -Idate)" \
            "$(date -Idate)" \
            banjo-x86_64-windows.zip \
            banjo-x86_64-linux.zip \
            banjo-aarch64-linux.zip \
            banjo-aarch64-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
